# Build settings
permalink   : /blog/:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

# source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: that_cannon_guy
description: "My name is (William) Cannon Lewis (II). I am interested in artificial intelligence, cognition, mathematics, and theatre. I occasionally write about these topics and anything else that catches my eye. I read my email."
keywords: "Jekyll, cannon, end2end, cannon lewis, cs, math"
url: http://cannon10100.github.io
baseurl: ""
# baseurl: ""

# google_analytics: UA-52446115-1
repo: http://github.com/cannon10100/cannon10100.github.io
disqus_shortname: "cannonlewis"
disqus_site_shortname: "thatcannonguy"

# Author settings
author:
  name      : (William) Cannon Lewis (II)
  job       : reader and developer
  bio       : "Fan of artificial intelligence, mathematics, reading, running, and laughing. I read my email"
  thumb     : /images/author.jpg
  email     : cannon10100@gmail.com
  url       : http://cannontwo.com
  github    : http://github.com/cannon10100
  twitter   : http://twitter.com/that_cannon_guy
  facebook  : http://facebook.com/cannon10100
  linkedin  : http://linkedin.com/in/cannonlewis2

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: assets/resume.pdf
    title: Resume
  # - slug: skills
  #   title: Skills
  - slug: chart
    title: Chart
  - slug: blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
