# Site settings
title: W. Cannon Lewis II
name: W. Cannon Lewis II's Blog
email: wcannon@rice.edu
author: W. Cannon Lewis II
description: Cannon's personal site.
url: cannontwo.com

# Build settings
permalink: :title/
sass:
    sass_dir: css
markdown: kramdown
mathjax: true
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class: 'highlight'

# Social
github_username: cannontwo
twitter_username: wcannontwo
linkedin_username: cannonlewis2
